### ISSUE TITLE
Script and Recording for Rev Harris

### ISSUE THREAD

**Issue by joejcollins** [blackradley/dinmore#21]
[Script - Rev. Robert Harris bust.docx](https://github.com/blackradley/dinmore/files/1263416/Script.-.Rev.Robert.Harris.bust.docx)

**Comment by thebeebs** [comment]
Recordings done. Now will create a voice package.

**Comment by thebeebs** [comment]
Voice is now recorded and can be found here: https://developdinmore.blob.core.windows.net/voicepackages/ReverendHarris-FrontDevice-v1.zip
