### ISSUE TITLE
Script and Recording for Preston Panorama

### ISSUE THREAD

**Issue by joejcollins** [blackradley/dinmore#22]
[Script - Joe Jenkinson painting.docx](https://github.com/blackradley/dinmore/files/1263420/Script.-.Joe.Jenkinson.painting.docx)

**Comment by thebeebs** [comment]
Recording done will now create a voice package

**Comment by thebeebs** [comment]
Voice package is now created and can be found here: https://developdinmore.blob.core.windows.net/voicepackages/PanoramaOfPreston-BelowPicture-v2.zip
