### ISSUE TITLE
Uploading audio package does not set the URL 

### ISSUE THREAD

**Issue by martinkearn** [blackradley/dinmore#55]
When you upload a new audio package, it should automatically set the URL to the newly uploaded package, but it does not

**Comment by martinkearn** [comment]
This is fixed in the 'develop' branch of Martin's fork as part of the API project (https://github.com/martinkearn/dinmore/commit/d3e026d1c7f6b073f0e188e3ae4f6a103c5c93d9). Not sure how to merge it back in without merging other file changes that are not required?

**Comment by joejcollins** [comment]
I am going with....
   git cherry-pick d3e026d1c7f6b073f0e188e3ae4f6a103c5c93d9
...I will tell you if it works.

**Comment by joejcollins** [comment]
It seems to work now.  Perhaps the dev site didn't build as quickly as I thought it should.
